### ISSUE TITLE
importing module pin

### ISSUE THREAD

**Issue by rara-mana** [ericmjl/protein-interaction-network#2]
`from pin import *`is still problematic & doesn't work (module not found error)

In `___init__.py,`_ the version number is expected to be  a string as "0.1.2" and is raising an error at this point. This gets fixed if one edits the file (after pip install) and changed it to a string.

**Comment by ericmjl** [comment]
@rara-mana I think I've updated the imports, such that we now do:

```python
from proteingraph import ProteinInteractionNetwork
```

Sorry about that - this was an old code base that is still in evolution as I develop it.

As for the version number, I've updated it, and will cut a patch release soon.

**Comment by ericmjl** [comment]
@rara-mana new release is up; if it doesn't work, please re-open this issue.
